services:
  postgresDB:
    image: postgres:latest
    secrets:
      # define the secret name
      - db_username
      - db_password
    environment:
      - "POSTGRES_PASSWORD_FILE: /run/secrets/db_password"
      - "POSTGRES_USER_FILE: /run/secrets/db_username"

  # another service using cli to add secrets
  centOS:
    image: centos
    deploy:
      replicas: 1
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    secrets:
      - source: my-random-secret

# file based secrets
# need to create the secret files first
secrets:
  db_username:
    file: ./postgres_user,txt
  db_password:
    file: ./postgres_password.txt
  # to use cli to add the secret (need to create the secret in the host node first)
  my-random-secret:
    external: true
