apiVersion: v1
kind: Pod
metadata:
  name: node-draining-test-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
  restartPolicy: OnFailure
