apiVersion: apps/v1
kind: DaemonSet # DaemonSet Object
metadata:
  name: logging # name of DaemonSet
spec:
  selector:
    matchLabels:
      app: httpd-logging # matchLabels must match the template labels
  template:
    metadata:
      labels:
        app: httpd-logging
    spec:
      containers:
      - name: webserver
        image: httpd
        ports:
        - containerPort: 80
