apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector # note: must be in lowercase
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector: # nodeSelector with disktype as label 
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodename
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: k8s-worker-03 # setting the nodeName to worker node
---
apiVersion: v1 # nodeSelector with Resource Requests
kind: Pod
metadata:
  name: frontend-app
spec:
  containers:
  - name: app
    image: alpine
    command:
    - sleep
    - '3600'
    resources:
      requests:
        memory: 64Mi
        cpu: 2000m # set smth to be greater than number of available cores 
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app-3
spec:
  containers:
  - name: app
    image: alpine
    command:
    - sleep
    - '3600'
    resources:
      requests:
        memory: 64Mi
        cpu: 1000m
