apiVersion: v1
kind: Pod
metadata:
  name: hc-probe
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    livenessProbe: # liveness probe
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe: # readiness probe
      httpGet:
        path: /
        port: 80 # change to another port that nginx is not on eg 9090 will fail the readiness probe
      initialDelaySeconds: 3
      periodSeconds: 3
