apiVersion: v1
kind: Pod
metadata:
  name: restart-always-pod # this pod will have increment counts in restarts 
spec:
  restartPolicy: Always # do not need to set this as always is default behaviour
  containers:
  - name: app
    image: alpine
    command: ["sleep", "20"] # container will stop after sleeping for 20s

---
apiVersion: v1
kind: Pod
metadata:
  name: onfailure-always-pod # this will only restart if failure/error of container
spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: alpine
    command: ["sleep", "20"] # in this case container goes to completed status, exit successfully (will not restart)
    # command: ['sh', '-c', 'sleep 20; DummyCommand'] # dummy command will cause this pod to error and restart will happen
---
apiVersion: v1
kind: Pod
metadata:
  name: never-always-pod
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: alpine
    command: ["sleep", "20"]
