apiVersion: v1
kind: Pod
metadata:
  name: lab-cm-env-demo
spec:
  containers:
  - name: cm-demo
    image: alpine
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    # define the env var and pass in the cm and secret
    - name: PLAYER_LIVES
      valueFrom:
        configMapKeyRef:
          name: lab-demo-cm # the name of the cm being referenced
          key: player_lives # the key to fetch and map the value
    - name: PROPERTIES_FILE_NAME
      valueFrom:
        configMapKeyRef:
          name: lab-demo-cm
          key: properties_file_name
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef: # to ref a secret
          name: lab-demo-secret # the name of the secret
          key: username # the key for the mapping
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lab-demo-secret
          key: password
