apiVersion: v1
kind: Pod
metadata:
  name: application-pod
spec:
  containers:
  - name: myapp-container # main app container
    image: busybox:1.28
    command: ["sh", "-c", "echo The app is running! && sleep 3600"]
  initContainers: # syntax to set init containers
  - name: init-myservice # init container
    image: busybox:1.28
    command: ["sh", "-c", "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 5; done"]
    # doing nslookup for a k8s service myservice 
  - name: init-mydb
    image: busybox:1.28
    command: ["sh", "-c", "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 5; done"]
