apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: liveness
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthcheck; sleep 60; rm -rf /tmp/healthcheck; sleep 600 # create folder slp 60s delete folder slp 600s
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthcheck
      initialDelaySeconds: 5
      periodSeconds: 5

---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-http
spec:
  containers:
  - name: nginx
    image: k8s.gcr.io/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
