apiVersion: rbac.authorization.k8s.io/v1
kind: Role # for ClusterRole just change to ClusterRole
metadata:
  namespace: development # not needed for ClusterRole manifest as ClusterRole is global not scoped to namespace
  name: pod-reader
rules: # the permissions
- apiGroups: [""]
  resources: ["pods", "pods/log"] # the resources type that this role can access
  verbs: ["get", "watch", "list", "update"] # what action this Role can perform on the resources
