apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # type is RoleBinding (scoped to namespace)
metadata:
  name: sa-pod-reader
  namespace: development
subjects:
- kind: ServiceAccount
  name: my-serviceaccount # the ref name when sa is created
  namespace: development
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
