apiVersion: apps/v1
kind: Deployment

{{- with .Values.customblock.author.companies }}
company:
{{- toYaml . | nindent 8 }}
{{- else }}
{{"Empty Array Passed In" | nindent 4}}
{{- end}}
{{- if .Values.customblock.author.enabled }}
{{"Custom enabled Field is set to true" | nindent 4}}
{{- else}}
{{"Custom enabled is set to false" | nindent 4}}
{{- end }}
  {{ "some random text here - " }} {{ "HELM" }}
  {{ .Values.customblock.author.name }}
  {{ .Values.customblock.author.address }}
  {{ .Values.customblock.author.email | default "using default as email is empty johndoe@email.com"}}
  {{ .Values.customblock.author.email | default "using default as email is empty johndoe@email.com" | nindent 2}}
  {{ .Values.customblock.author.email | default "using default as email is empty johndoe@email.com" | upper | nindent 4}}
  {{ .Values.customblock.author.email | default "using default as email is empty johndoe@email.com" | upper | quote | nindent 8}}

  {{ "Values from Chart" }}
  {{ .Chart.AppVersion }}
  {{ .Chart.Keywords }}
  {{ .Chart.Maintainers }}

metadata:
  name: {{ include "my-first-chart.fullname" . }}
  labels:
    {{- include "my-first-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-first-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-first-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-first-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
