version: "3"
services:
  python_app:
    build:
      context: .
      dockerfile: dockerfile.python
      args:
        - BASE_IMAGE=python:3.9
        - APP_VERSION=2.5
    environment:
      - DEBUG=true
    image: ngyewkong/python_app:2.0

  node_app:
    build:
      context: .
      dockerfile: dockerfile.node
      args:
        - BASE_IMAGE=node:21
        - APP_NAME=node-sample-app
    environment:
      - NODE_ENV=development
    image: ngyewkong/node_app:2.0
