apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: network-policy # not the default namespace
  labels:
    app: frontend # the labels
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: network-policy # not the default namespace
  labels:
    app: client
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command:
    - sleep
    - '3600'
