FROM mcr.microsoft.com/dotnet/sdk:7.0 AS builder

WORKDIR /jenkins/sample_project/src
COPY jenkins/sample_project/src/Pi.Math/Pi.Math.csproj ./Pi.Math/
COPY jenkins/sample_project/src/Pi.Runtime/Pi.Runtime.csproj ./Pi.Runtime/
COPY jenkins/sample_project/src/Pi.Web/Pi.Web.csproj ./Pi.Web/

WORKDIR /jenkins/sample_project/src/Pi.Web
RUN dotnet restore

# app image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

EXPOSE 80
ENTRYPOINT ["dotnet", "Pi.Web.dll"]
CMD ["-m", "console", "-dp", "6"]
