apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes: # set the volume to be used by the pod
  - name: hostpath-vol
    hostPath: # volume type
      path: /var/tmp # the /var/tmp must exist on the k8s node
  containers:
  - name: hostpath-pod
    image: 'busybox'
    command: ["/bin/sh", "-c", "echo Hello Team, This is Sample File for HostVolume - $(date) >> /output/output.txt"] # write a file output.txt to the node the pod is running on at /var/tmp
    volumeMounts:
    - name: hostpath-vol
      mountPath: /output # final dir that will read/write data to /var/tmp/ in the k8s node
